apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: worldmodelers-web-worker
  name: worldmodelers-praise-web-worker
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: worldmodelers-web-worker
    spec:
      containers:
      - name: praise-web-worker
        image: worldmodelers.cse.sri.com/praise-web-worker
        command: ["/entrypoint.sh"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: artifactory-secret
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: worldmodelers-web
  name: worldmodelers-redis
spec:
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        command: ["redis-server", "--appendonly yes", "--dir /data"]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -h $(hostname) ping
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-scratch
          mountPath: /data
      volumes:
      - name: redis-scratch
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: worldmodelers-web-service
  namespace: world-builders
  labels:
    app: worldmodelers-web
spec:
  selector:
    app: worldmodelers-web-server
  ports:
    - targetPort: 8080
      port: 80
      name: command
      protocol: TCP
