apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: worldmodelers-web-server
  name: worldmodelers-praise-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worldmodelers-web-server
    spec:
      containers:
      - name: praise-web-ser
        image: worldmodelers.cse.sri.com/praise-web-server:v2
        command: ["/entrypoint.sh", "praise-server"]
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: artifactory-secret
---
apiVersion: v1
kind: Service
metadata:
  name: worldmodelers-web-service
  labels:
    app: worldmodelers-web
spec:
  selector:
    app: worldmodelers-web-server
  ports:
    - targetPort: 3000
      port: 80
      name: command
      protocol: TCP
